### ISSUE TITLE
heic conversion fails on Debian/Ubuntu

### ISSUE THREAD

**Issue by ruphy** [thumbsup/downsize#14]
Hi,

the ImageMagick debian package does not contain the "magick" command in PATH. This makes all thumbsup's heic conversions fail with an ENOENT error.

A quick and dirty solution for my system (where I installed thumbsup globally) was to simply edit the file:
`/usr/local/lib/node_modules/thumbsup/node_modules/thumbsup-downsize/lib/image/heic.js`

modifying the convertToJpeg function from

```.js
function convertToJpeg (source, target, done) { 
  const args = [ 'convert', source, target ]
  exec('magick', args, done)
} 
```
to
```.js
function convertToJpeg (source, target, done) { 
  const args = [ source, target ]
  exec('convert', args, done)
} 
```

and similarly the function convertToSRGB:
```.js
function convertToSRGB (target, done) {
  const args = [ '-profile', SRGB_ICM_PATH, target ]
  exec('mogrify', args, done)
}
```

With this fix, thumbsup correctly processes my gallery.

**Comment by ruphy** [comment]
I spoke way too soon. I realized that this binary mismatch might be caused by the fact that I have installed ImageMagick 6.9, not 7.x. This version allows for the conversion to take place (which I tested manually), but probably fails in the colorspace adjustment or subsequent automated process (as I only get an empty file at the end of the process).
I am currently compiling the 7.0 version to check whether it provides a real fix.

UPDATE: I failed to compile a proper working version with heic support (in spite of --with-heic=yes) and I ran out of time for this week. However, I confirm that the command "magick" is now present.

**Comment by rprieto** [comment]
Hi, thanks for the bug report. I believe ImageMagick used to ship different commands as separate binaries (`convert`, `mortify`...). Version 7 now also has a single binary that you can call as `magick convert...`.

I will add something in the docs that says it must be version 7.

**Comment by rprieto** [comment]
Hi @ruphy, you can see how HEIC support is compiled in the thumbsup Docker image here: https://github.com/thumbsup/docker/blob/master/runtime-alpine/Dockerfile

**Comment by rprieto** [comment]
I'm closing this issue for now, please re-open it if needed.
