### ISSUE TITLE
Feature Request:  HW Acceleration support for VAAPI

### ISSUE THREAD

**Issue by dravenst** [thumbsup/downsize#25]
Great continuing work on this project!

I'm wondering if you would consider enabling the option to use the ffmpeg options for vaapi hardware acceleration for video decoding/encoding.

On my Synology/Linux environment, there is VAAPI HW accelerator support that can be enabled through some additional ffmpeg switches.  It increases performance an order of magnitude.  In the example below, I'm capping the output size at 1920 to downsize from 4K too.  vaapi doesn't support directly the quality setting, but it does allow bitrate adjustments.

`ffmpeg -y -nostdin -hwaccel_device /dev/dri/renderD128 -hwaccel vaapi -hwaccel_output_format vaapi -i "$FILE_ORIG" -movflags +faststart -b:a 160k -vf "format=nv12|vaapi,hwupload,fps=29.97,scale_vaapi=1920:-1" -c:v h264_vaapi -f mp4 "$FILE_DEST"`

**Comment by rprieto** [comment]
Hi, this is very interesting! I'd like to add support for it.

I'm not familiar enough with Vaapi hardware acceleration, so I have a few questions:

- What kind of performance boost are you seeing?
- Can these flags be used on all source videos, regardless of the encoding?
- Is is possible to tell if hardware acceleration is available, for example when `downsize` initializes? I assume the flags fail if Vaapi is not available, so it would have to be an option otherwise.

Thanks again!

**Comment by dravenst** [comment]
The performance boost for me is pretty significant on the Synology (at least 10x improvement), but I'm not sure how it performs elsewhere.  I suspect it will generally be a similar boost for other processors.

I haven't run into any issues with different video source types to-date, but I'm mostly using h.264 content at 4K for the input.  I've tested these flags with both HD and 4K videos and they work fine. 

VAAPI works well with Intel/AMD chips, and there is a similar set of flags for Nvidia graphics cards too.  (see ffmpeg CUDA/NVENC/NVDEC).  (ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i input -c:v h264_nvenc -preset slow output)

I'm not familiar with how to auto-detect.  

One other idea is you could potentially allow the user more flexibility to customize the ffmpeg options rather than trying to handle the config for vaapi (and cuda)?  This would allow users to also customize separately for other scenarios. 

Is scaling down the video size an option you would consider too?  This has been important for my own needs (e.g. to resize to 720p for web-based videos).

**Comment by rprieto** [comment]
That's a huge improvement! I like the idea of providing a flag like `--hardware-acceleration vaapi|cuda` but I'd have to see how easy/complex it is to generate the right ffmpeg command.

Customizing the ffmpeg command is interesting. We already offer it for pictures with with `--gm-args`. However it looks like Vaapi requires changes in multiple args, so it's not a matter of appending a few arguments. It might require completely replacing the command with a user-provided command, which gets tricky. It would ignore all the logic here: https://github.com/thumbsup/downsize/blob/master/lib/video/ffargs.js

For the last suggestion: scaling down is also a good idea. What do you think about a new flag to control the output resolution? Could you please create a separate issue for this? It sounds easy to tackle separately.

**Comment by rprieto** [comment]
In fact there is an existing issue about video resolution on the main repo: https://github.com/thumbsup/thumbsup/issues/200

**Comment by rprieto** [comment]
Closed by PR #29
