### ISSUE TITLE
Doesn't always work for .MOV files on Mac

### ISSUE THREAD

**Issue by galactictech** [thumbsup/downsize#26]
I have some .mov files which are not being downsized correctly on my Mac. That is, the output won't play in the Finder or Quicktime. I found I could fix this by calling ffmpeg with `-pix_fmt yuv420p` as described in the ffmpeg docs at http://trac.ffmpeg.org/wiki/Encode/H.264. For the moment, I patched my local copy of ffmpeg by adding this to exports.prepare() in ffargs.js (mimicking, and just after, the code for .mts files):
>   } else if (path.extname(source).toLowerCase() === '.mov') {
      args.push('-pix_fmt', 'yuv420p')
  }

**Comment by kcjl519** [comment]
Actually an extended problem with not playing on finder, is that it won't work on mobile safari / chrome, and desktop safari.

I have tried with manually adding `-pix_fmt yuv420p` and it resolves the problem

Also the filename may not always be .mov.
I have videos shot on iphone that is saved as .mov and works without pix_fmt and I also have videos shot with DJI Mimo that's saved as .mp4 but doesn't work without pix_fmt..

**Comment by rprieto** [comment]
Hi @galactictech. First of all apologies for the very slow reply. Thank you for raising this and for providing a fix. I can reproduce the issue locally as well.

@kcjl519 based on your comment we might need more than a check on the `.mov` extension. I will investigate this as a priority. Do you have any suggestion? I wonder if it's safe to add `-pix_fmt yuv420p` systematically.
