### ISSUE TITLE
Consider "-movflags +faststart"

### ISSUE THREAD

**Issue by tribut** [thumbsup/downsize#4]
Normally, metadata in an MP4 container is stored in a single place (the moov atom) at the end of the file. Thus, the playback cannot start until the whole video is downloaded. Traditionally, special tools where needed to move the metadata to the beginning, allowing web browser to immediately start playback (qt-faststart, MP4Box).

A few years ago, ffmpeg has added support for this using the `-movflags +faststart` option. I'm not sure if most users have recent enough versions of ffmpeg installed (even the version in Debian stable is recent enough) or if there is a fallback needed, but it seems reasonable to add it.

**Comment by rprieto** [comment]
Thanks, I learnt something new!  That sounds very reasonable to me.
*Edit: let me know if you're happy to make PR otherwise I'll add these in soon.*
